// Mocks generated by Mockito 5.0.10 from annotations
// in price_action_orders/test/data/repositories/market_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:price_action_orders/data/datasources/market_datasource.dart'
    as _i3;
import 'package:price_action_orders/domain/entities/bookticker.dart' as _i5;
import 'package:price_action_orders/domain/entities/ticker.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeTicker extends _i1.Fake implements _i2.Ticker {}

/// A class which mocks [MarketDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarketDataSource extends _i1.Mock implements _i3.MarketDataSource {
  MockMarketDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i4.Stream<_i5.BookTicker>> getBookTickerStream(
          _i2.Ticker? ticker) =>
      (super.noSuchMethod(Invocation.method(#getBookTickerStream, [ticker]),
              returnValue: Future<_i4.Stream<_i5.BookTicker>>.value(
                  Stream<_i5.BookTicker>.empty()))
          as _i4.Future<_i4.Stream<_i5.BookTicker>>);
  @override
  _i4.Future<void> cacheLastTicker(_i2.Ticker? ticker) =>
      (super.noSuchMethod(Invocation.method(#cacheLastTicker, [ticker]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<_i2.Ticker> getLastTicker() =>
      (super.noSuchMethod(Invocation.method(#getLastTicker, []),
              returnValue: Future<_i2.Ticker>.value(_FakeTicker()))
          as _i4.Future<_i2.Ticker>);
}
