// Mocks generated by Mockito 5.0.15 from annotations
// in price_action_orders/test/data/repositories/trade_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:price_action_orders/data/datasources/trade_datasource.dart'
    as _i4;
import 'package:price_action_orders/domain/entities/order_cancel_request.dart'
    as _i7;
import 'package:price_action_orders/domain/entities/order_cancel_response.dart'
    as _i3;
import 'package:price_action_orders/domain/entities/order_request.dart' as _i6;
import 'package:price_action_orders/domain/entities/order_response_full.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeOrderResponseFull_0 extends _i1.Fake
    implements _i2.OrderResponseFull {}

class _FakeCancelOrderResponse_1 extends _i1.Fake
    implements _i3.CancelOrderResponse {}

/// A class which mocks [TradeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTradeDataSource extends _i1.Mock implements _i4.TradeDataSource {
  MockTradeDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.OrderResponseFull> postOrder(_i6.OrderRequest? order) =>
      (super.noSuchMethod(Invocation.method(#postOrder, [order]),
              returnValue: Future<_i2.OrderResponseFull>.value(
                  _FakeOrderResponseFull_0()))
          as _i5.Future<_i2.OrderResponseFull>);
  @override
  _i5.Future<_i3.CancelOrderResponse> cancelOrder(
          _i7.CancelOrderRequest? cancelOrder) =>
      (super.noSuchMethod(Invocation.method(#cancelOrder, [cancelOrder]),
              returnValue: Future<_i3.CancelOrderResponse>.value(
                  _FakeCancelOrderResponse_1()))
          as _i5.Future<_i3.CancelOrderResponse>);
  @override
  String toString() => super.toString();
}
